### ISSUE TITLE
[Minor] Is error message correct?

### ISSUE THREAD

**Issue by audiodude** [derhuerst/gemini#15]
https://github.com/derhuerst/gemini/blob/873b457889def5c9435ae943283a5f09f275a62e/lib/response-parser.js#L25

It reads `invalid Gemini request` but shouldn't it say `invalid Gemini response`? I'm just a bit confused because I'm getting this error and I'm not sure if the problem is with the request or response (I assume the latter). Thanks!

**Comment by derhuerst** [comment]
Yes, indeed, this should be "invalid Gemini response"!

**Comment by derhuerst** [comment]
Fix published as `@derhuerst/gemini@1.3.1`. 🎉

**Comment by audiodude** [comment]
Thanks so much for the quick fix!
